<a href="https://colab.research.google.com/github/NikhilSajimon/ICT-Notes/blob/main/python_25082025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##NumPy and Pandas

In [ ]:

# Arrays are a collection of elements values that can have one or more dimensions
# An array of one dimension is called a vector while having two dimensions is called a matrix
# Numpu array can specify and support various data types, any array created in numpy should use only one desired datatype
# This approach requires less memmory and is efficient and fast


In [ ]:
import numpy as np

In [ ]:
x = np.array([12, 14, 23, 45, 105])
x

array([ 12,  14,  23,  45, 105])

In [ ]:
type(x)

numpy.ndarray

numpy methods

In [ ]:
# to find the shape of the array
x.shape

(5,)

In [ ]:
# to find the dimension of the array
x.ndim

1

In [ ]:
# to find the datatype of elements in the array
x.dtype

dtype('int64')

In [ ]:
# creating a two dimensional array
y = np.array([
    [1, 2, 3],
    [4, 5, 6.0],
    [7, 8, 9]
])

y

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
y.shape

(3, 3)

In [ ]:
y.size

9

In [ ]:
y.dtype

dtype('float64')

In [ ]:
xy = np.array([1.5, 2.3, 4.6, 7.5], dtype = np.int64)
xy

array([1, 2, 4, 7])

In [ ]:
xy + 9

array([10, 11, 13, 16])

In [ ]:
xy - 2

array([-1,  0,  2,  5])

In [ ]:
xy * 3

array([ 3,  6, 12, 21])

In [ ]:
xy / 2

array([0.5, 1. , 2. , 3.5])

In [ ]:
xy ** 3

array([  1,   8,  64, 343])

In [ ]:
# creating an arrays of zeros
zeros = np.zeros((3,4), dtype=np.int64)
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# creating an array of ones
ones = np.ones((4,4), dtype=np.int64)
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
# The numpy.eye() function in Python's NumPy library creates a two-dimensional array (matrix) with ones on a specified diagonal and zeros elsewhere.
# This function is commonly used to generate identity matrices, which are square matrices with ones on the main diagonal and zeros everywhere else.
a3 = np.eye(4)
a3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Constructing Diagonal Arrays:
# When provided with a 1-dimensional array, numpy.diag() constructs a 2-dimensional array (matrix)
# where the elements of the input 1-D array are placed on the specified diagonal,
# and all other elements are set to zero.

a4 = np.diag([100, 200, 300, 50])
a4

array([[100,   0,   0,   0],
       [  0, 200,   0,   0],
       [  0,   0, 300,   0],
       [  0,   0,   0,  50]])

In [ ]:
# The numpy.arange() function is a fundamental tool within the NumPy library in Python,
# used for creating arrays with evenly spaced values within a specified interval.
# It functions similarly to Python's built-in range() function but returns a NumPy array,
# which is optimized for numerical computations and integrates seamlessly with other NumPy operations.
# syntax -  numpy.arange([start, ]stop, [step, ], dtype=None)

a5 = np.arange(10, 25, 2, dtype=np.float64)
a5

array([10., 12., 14., 16., 18., 20., 22., 24.])

In [ ]:
# The numpy.reshape() function in Python's NumPy library is used to change the shape of an array without altering its data.
# This function returns a new array (often a view of the original data if possible) with the specified new shape,
# provided the total number of elements remains the same.
# syntax = array.reshape(new_shape) or numpy.reshape(array, new_shape)

np.reshape(a5, (4,2))

array([[10., 12.],
       [14., 16.],
       [18., 20.],
       [22., 24.]])

In [ ]:
a5.reshape(2, 4)

array([[10., 12., 14., 16.],
       [18., 20., 22., 24.]])

The random module in Python is a built-in module used to generate pseudo-random numbers.

In [ ]:
# np.random.random(), is a function within the NumPy library that generates an array of specified shape
# and fills it with random floating-point numbers.
a6 = np.random.random((4,4))
a6

array([[0.16714515, 0.81937628, 0.78011061, 0.0896989 ],
       [0.30483475, 0.46627066, 0.60896138, 0.13595607],
       [0.82841812, 0.70053173, 0.03418816, 0.2013992 ],
       [0.76294687, 0.82537813, 0.44915731, 0.78970276]])

In [ ]:
# The numpy.random.randint() function is used to generate random integers within a specified range.
# Syntax: numpy.random.randint(low, high=None, size=None, dtype=int)

a7 = np.random.randint(10, 100, size=(5,5))
a7

array([[13, 84, 20, 36, 50],
       [24, 23, 43, 46, 17],
       [82, 38, 13, 56, 17],
       [82, 41, 71, 49, 35],
       [55, 21, 25, 67, 43]])

In [ ]:
a7[0]

array([13, 84, 20, 36, 50])

In [ ]:
a7[-1]

array([55, 21, 25, 67, 43])

In [ ]:
a7[1:4]

array([[24, 23, 43, 46, 17],
       [82, 38, 13, 56, 17],
       [82, 41, 71, 49, 35]])

In [ ]:
a7[2, 2]

np.int64(13)

In [ ]:
a7[1:4, 1:4]

array([[23, 43, 46],
       [38, 13, 56],
       [41, 71, 49]])

In [ ]:
a7[:,2]

array([20, 43, 13, 71, 25])

In [ ]:
z = np.random.randint(1, 100, (4,4))
z

array([[98, 72, 73, 69],
       [ 9, 35, 80, 28],
       [ 5, 17, 67, 27],
       [47, 46, 66,  8]])

In [ ]:
# np.sum()
# Calculates the sum of all array elements or along a specified axis.
# syntax - np.sum(arr, axis=0) axis= (0 for column, 1 for row)

np.sum(z, 1)

array([312, 152, 116, 167])

In [ ]:
np.sum(z, 0)

array([159, 170, 286, 132])

In [ ]:
np.sum(z)

np.int64(747)

In [ ]:
# np.where()
# The np.where() function is a powerful and very useful NumPy function
# that acts like a vectorized, or element-wise, if-else statement for NumPy arrays.

# Used for data cleaning and handling missing values based on conditions.

# Returns elements chosen from two arrays based on a condition. Useful for conditional assignment.
# np.where(condition, x, y)

np.where(z > 50, z, 0)

array([[98, 72, 73, 69],
       [ 0,  0, 80,  0],
       [ 0,  0, 67,  0],
       [ 0,  0, 66,  0]])

In [ ]:
# np.corrcoef(x, y)
# Calculates the Pearson product-moment correlation coefficients (measures the linear relationship between two datasets).
# np.corrcoef(x, y)

u = np.random.randint(1, 100, (1,10))
v = np.random.randint(1, 100, (1,10))

np.corrcoef(u, v)

array([[ 1.       , -0.2577149],
       [-0.2577149,  1.       ]])

In [ ]:
# np.percentile(a, q, axis=None)
# Computes the q-th percentile of the data along the specified axis.
# Useful for finding quartiles (e.g., q=25,50,75).
# np.percentile(data, 50)

print(u)
print(np.percentile(u, 25))
print(np.percentile(u, 50))
print(np.percentile(u, 75))

[[73 70 47 94 58 85 15 81 87 54]]
55.0
71.5
84.0


In [ ]:
# np.cumsum(a, axis=None)
# Calculates the cumulative sum of the elements along a given axis.
# np.cumsum(data)

print(z)
print(np.cumsum(z, 0))
print(np.cumsum(z, 1))

[[98 72 73 69]
 [ 9 35 80 28]
 [ 5 17 67 27]
 [47 46 66  8]]
[[ 98  72  73  69]
 [107 107 153  97]
 [112 124 220 124]
 [159 170 286 132]]
[[ 98 170 243 312]
 [  9  44 124 152]
 [  5  22  89 116]
 [ 47  93 159 167]]


In [ ]:
# np.std(a, axis=None)
# Computes the standard deviation, which measures the amount of variation or dispersion from the mean.
# np.std(data)

np.std(z, 1)

array([11.64044673, 26.04803256, 23.28089345, 21.05201891])

In [ ]:
np.std(z, 0)

array([37.41239768, 19.93113143,  5.59016994, 22.25982929])

In [ ]:
# np.var(a, axis=None)
# Computes the variance, which is the average of the squared differences from the mean (standard deviation squared).
# np.var(data)

np.var(z, 0)

array([1399.6875,  397.25  ,   31.25  ,  495.5   ])

In [ ]:
np.var(z, 1)

array([135.5   , 678.5   , 542.    , 443.1875])

In [ ]:
# np.mean(a, axis=None)
# Calculates the arithmetic mean (average) of the array elements.
# You can specify the axis to get the mean across rows or columns.
# np.mean(data)


# np.median(a, axis=None)
# Computes the median (the middle value of the sorted data).
# np.median(data)


# np.average(a, axis=None, weights=None)
# Computes the weighted average. Very useful when different data points have different levels of importance.
# np.average(data, weights=w)

print(np.mean(z, 0))
print(np.mean(z, 1))
print(np.mean(z))

print(np.median(z, 0))
print(np.median(z, 1))
print(np.median(z))

[39.75 42.5  71.5  33.  ]
[78.   38.   29.   41.75]
46.6875
[28.  40.5 70.  27.5]
[72.5 31.5 22.  46.5]
46.5


In [ ]:
# try out these functions
# vstack
# hstack
# sort
# concatenate
# transpose
# full
# sqrt
# copy
# view

##Pandas

In [ ]:
# Core Usages of Pandas

# Data Modeling and Storage:
# Pandas provides the DataFrame structure, which is the standard way to represent and
# store tabular data (like a spreadsheet or SQL table) in Python, giving data meaning
# through labeled rows and columns.

# Data Loading and Export:
# It acts as the primary tool for moving data in and out of Python.
# Pandas can seamlessly read data from various file types (CSV, Excel, SQL databases, JSON) and
# write processed data back out to the same formats.

# Data Cleaning:
# Pandas facilitates rapid data quality management. This includes identifying and
# handling missing values (e.g., ignoring or filling them), removing duplicate entries,
# and correcting inconsistencies across large datasets.

# Data Slicing and Filtering:
# It allows for highly intuitive and powerful ways to select subsets of data.
# Users can easily filter rows based on complex conditions (e.g., all customers over 50 years old in a specific city)
#  or select specific columns by name.

# Aggregation and Summarization:
# Pandas is built for summarizing data.
# The grouping capability allows for quick calculations of metrics (like totals, counts, or averages)
# across different categories (e.g., finding the average sales per region).

# Time Series Analysis:
# It has robust native capabilities for working with data indexed by time,
# making it the go-to tool for tasks like handling irregular time intervals,
# generating date ranges, and preparing financial or sensor data for analysis.

In [ ]:
# provides series(1D) and dataframe structures(2D)

In [ ]:
import pandas as pd

In [ ]:
pd.Series([1, 2, 3, 4, np.nan, 6, 7])

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
5    6.0
6    7.0
dtype: float64

In [ ]:
df = pd.DataFrame(np.random.randint(0, 100, (5,5)), columns=['A', 'B', 'C', 'D', 'E'])
df

A   B   C   D   E
0  53   6  55  27  22
1  44  73  13  42   0
2  97  70  89  84  22
3  81  45  50  91  74
4  26  10  37  26  60

In [ ]:
data = {
    'calories': [400, 350, 380, 410, 500, 530, 580],
    'duration': [10, 20, 30, 40, 50, 60, 70]
}

df2 = pd.DataFrame(data, index=['day 1', 'day 2','day 3', 'day 4', 'day 5', 'day 6', 'day 7'])
df2

calories  duration
day 1       400        10
day 2       350        20
day 3       380        30
day 4       410        40
day 5       500        50
day 6       530        60
day 7       580        70

In [ ]:
df2['calories']


day 1    400
day 2    350
day 3    380
day 4    410
day 5    500
day 6    530
day 7    580
Name: calories, dtype: int64

In [ ]:
df2.iloc[0:5]

calories  duration
day 1       400        10
day 2       350        20
day 3       380        30
day 4       410        40
day 5       500        50

In [ ]:
df2.loc[:'day 5']

calories  duration
day 1       400        10
day 2       350        20
day 3       380        30
day 4       410        40
day 5       500        50

In [ ]:
# set_index and reset_index functions
# data = {'User_ID': [101, 102, 103],
#         'Name': ['Alice', 'Bob', 'Charlie'],
#         'Score': [85, 92, 78]}
# df = pd.DataFrame(data)

# # Set 'User_ID' as the new index
# df_indexed = df.set_index('User_ID')
# print(df_indexed)


# level:	Only removes the specified level(s) of a MultiIndex (Hierarchical Index).
# drop:	(Default: False) If True, the current index is discarded instead of being added as a new column.
# inplace:	(Default: False) If True, the operation modifies the DataFrame in place.

In [ ]:
df2.reset_index(drop=False)
df2.reset_index(drop=True)

calories  duration
0       400        10
1       350        20
2       380        30
3       410        40
4       500        50
5       530        60
6       580        70

In [ ]:
# The read_csv() function is the most essential and frequently used function in
# the Pandas library. It is used to read data from a comma-separated values (CSV) file
# and convert it directly into a DataFrame object.

In [ ]:
url = 'https://docs.google.com/spreadsheets/d/1VdgNwORHh4HlimuuEgrsixRgko2Gi1YdnlUYAnkPFR8/export?format=csv&gid=0'
df3 = pd.read_csv(url)
df3

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
df4 = pd.read_csv('/content/data - Sheet1.csv')
df4

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
# df.head() and df.tail() are two of the most frequently used methods in Pandas
# for quickly inspecting the structure and content of a DataFrame.
# They provide a quick preview without having to print the entire dataset.

# Usage: df.head(n)
# Parameter: n (integer) specifies the number of rows to return from the top.
# Default: If you call df.head() without any argument,
# it defaults to returning the first 5 rows (n=5).

In [ ]:
df4.head(10)

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0

In [ ]:
df4.tail()

Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
# shape of data frame
df4.shape

(169, 4)

In [ ]:
# Total datapoints in th df
df4.size

676

In [ ]:
# Information about the df
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


In [ ]:
df4.describe()

Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [ ]:
# df.isna() is a very important method in Pandas used for detecting missing values
#  (often represented as NaN, Not a Number) within a DataFrame.
# Output: It returns a Boolean DataFrame of the exact same size and shape as the original DataFrame.
# True: Indicates that the element in that position is a missing value (NaN).
# False: Indicates that the element has a valid, non-missing value.

df4.isna()

Duration  Pulse  Maxpulse  Calories
0       False  False     False     False
1       False  False     False     False
2       False  False     False     False
3       False  False     False     False
4       False  False     False     False
..        ...    ...       ...       ...
164     False  False     False     False
165     False  False     False     False
166     False  False     False     False
167     False  False     False     False
168     False  False     False     False

[169 rows x 4 columns]

In [ ]:
df4.isna().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

In [ ]:
df4[df4['Calories']<= 100]

Duration  Pulse  Maxpulse  Calories
89         20     83       107      50.3
93         15     80       100      50.5
100        20     95       112      77.7
104        30     92       108      92.7
107        30     90       120      86.2

In [ ]:
df4[(df4['Calories']<= 100) & (df4['Duration'] == 20)]

Duration  Pulse  Maxpulse  Calories
89         20     83       107      50.3
100        20     95       112      77.7

In [ ]:
df4.drop(165)

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
163        45    100       140     280.9
164        60    105       140     290.8
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[168 rows x 4 columns]

In [ ]:
df4.drop(['Calories'], axis=1)

Duration  Pulse  Maxpulse
0          60    110       130
1          60    117       145
2          60    103       135
3          45    109       175
4          45    117       148
..        ...    ...       ...
164        60    105       140
165        60    110       145
166        60    115       145
167        75    120       150
168        75    125       150

[169 rows x 3 columns]

In [ ]:
# unique values in each column
df4.nunique()

Duration     16
Pulse        47
Maxpulse     57
Calories    142
dtype: int64

In [ ]:
df4['Duration'].unique()

array([ 60,  45,  30,  80,  20, 210, 160, 180, 150, 300,  90, 120, 270,
        15,  25,  75])

In [ ]:
df4['Duration'].value_counts()

Duration
60     79
45     35
30     16
20      9
90      8
150     4
180     3
120     3
75      2
160     2
210     2
15      2
80      1
300     1
270     1
25      1
Name: count, dtype: int64

In [ ]:
df4.groupby('Duration')['Calories'].mean()

Duration
15       87.350000
20      151.600000
25      244.200000
30      192.125000
45      273.236364
60      339.675000
75      325.400000
80      643.100000
90      541.800000
120     666.833333
150     939.400000
160     943.700000
180     733.600000
210    1618.200000
270    1729.000000
300    1500.200000
Name: Calories, dtype: float64

In [ ]:
df4['Calories per minute'] = df4['Calories'] / df4['Duration']

In [ ]:
df4.head(10)

Duration  Pulse  Maxpulse  Calories  Calories per minute
0        60    110       130     409.1             6.818333
1        60    117       145     479.0             7.983333
2        60    103       135     340.0             5.666667
3        45    109       175     282.4             6.275556
4        45    117       148     406.0             9.022222
5        60    102       127     300.0             5.000000
6        60    110       136     374.0             6.233333
7        45    104       134     253.3             5.628889
8        30    109       133     195.1             6.503333
9        60     98       124     269.0             4.483333

In [ ]:
df4['Duration in hours'] = df4.Duration / 60
df4.head()

Duration  Pulse  Maxpulse  Calories  Calories per minute  Duration in hours
0        60    110       130     409.1             6.818333               1.00
1        60    117       145     479.0             7.983333               1.00
2        60    103       135     340.0             5.666667               1.00
3        45    109       175     282.4             6.275556               0.75
4        45    117       148     406.0             9.022222               0.75

In [ ]:
# Seaborn is often used with built-in example datasets that are
# helpful for learning and demonstrating its plotting capabilities.
# These datasets are readily available and can be loaded directly using the seaborn.load_dataset() function

In [ ]:
import seaborn as sns
df5 = sns.load_dataset('titanic')

In [ ]:
df5

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [ ]:
df5.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

In [ ]:
df5.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [ ]:
df5.shape

(891, 15)

In [ ]:
df5.size

13365

In [ ]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [ ]:
df5.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
df5.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df5[df5['age'] >= 60]

survived  pclass     sex   age  sibsp  parch      fare embarked   class  \
33          0       2    male  66.0      0      0   10.5000        S  Second   
54          0       1    male  65.0      0      1   61.9792        C   First   
96          0       1    male  71.0      0      0   34.6542        C   First   
116         0       3    male  70.5      0      0    7.7500        Q   Third   
170         0       1    male  61.0      0      0   33.5000        S   First   
252         0       1    male  62.0      0      0   26.5500        S   First   
275         1       1  female  63.0      1      0   77.9583        S   First   
280         0       3    male  65.0      0      0    7.7500        Q   Third   
326         0       3    male  61.0      0      0    6.2375        S   Third   
366         1       1  female  60.0      1      0   75.2500        C   First   
438         0       1    male  64.0      1      4  263.0000        S   First   
456         0       1    male  65.0      0      0   26.5500        S   First   
483         1       3  female  63.0      0      0    9.5875        S   Third   
493         0       1    male  71.0      0      0   49.5042        C   First   
545         0       1    male  64.0      0      0   26.0000        S   First   
555         0       1    male  62.0      0      0   26.5500        S   First   
570         1       2    male  62.0      0      0   10.5000        S  Second   
587         1       1    male  60.0      1      1   79.2000        C   First   
625         0       1    male  61.0      0      0   32.3208        S   First   
630         1       1    male  80.0      0      0   30.0000        S   First   
672         0       2    male  70.0      0      0   10.5000        S  Second   
684         0       2    male  60.0      1      1   39.0000        S  Second   
694         0       1    male  60.0      0      0   26.5500        S   First   
745         0       1    male  70.0      1      1   71.0000        S   First   
829         1       1  female  62.0      0      0   80.0000      NaN   First   
851         0       3    male  74.0      0      0    7.7750        S   Third   

       who  adult_male deck  embark_town alive  alone  
33     man        True  NaN  Southampton    no   True  
54     man        True    B    Cherbourg    no  False  
96     man        True    A    Cherbourg    no   True  
116    man        True  NaN   Queenstown    no   True  
170    man        True    B  Southampton    no   True  
252    man        True    C  Southampton    no   True  
275  woman       False    D  Southampton   yes  False  
280    man        True  NaN   Queenstown    no   True  
326    man        True  NaN  Southampton    no   True  
366  woman       False    D    Cherbourg   yes  False  
438    man        True    C  Southampton    no  False  
456    man        True    E  Southampton    no   True  
483  woman       False  NaN  Southampton   yes   True  
493    man        True  NaN    Cherbourg    no   True  
545    man        True  NaN  Southampton    no   True  
555    man        True  NaN  Southampton    no   True  
570    man        True  NaN  Southampton   yes   True  
587    man        True    B    Cherbourg   yes  False  
625    man        True    D  Southampton    no   True  
630    man        True    A  Southampton   yes   True  
672    man        True  NaN  Southampton    no   True  
684    man        True  NaN  Southampton    no  False  
694    man        True  NaN  Southampton    no   True  
745    man        True    B  Southampton    no  False  
829  woman       False    B          NaN   yes   True  
851    man        True  NaN  Southampton    no   True